### ISSUE TITLE
Get wrong result

### ISSUE THREAD

**Issue by aeimer** [IonicaBizau/url-local#6]
Hi @IonicaBizau,

I am using the protractor-plugin https://www.npmjs.com/package/protractor-screenshoter-plugin it is using https://www.npmjs.com/package/image-to-ascii which uses https://www.npmjs.com/package/lwipify

Lwipify checks with your plugin url-remote if the requested image is a web-resource or a local one.

But there is a bug, which lets fail the protractor plugin:
```bash
{ AssertionError: protocol mismatch
    at parseOptions (/vagrant/app/webFrontend/node_modules/follow-redirects/create.js:131:10)
    at H.request (/vagrant/app/webFrontend/node_modules/follow-redirects/create.js:108:19)
    at tinyreq (/vagrant/app/webFrontend/node_modules/tinyreq/lib/index.js:69:65)
    at lwipify (/vagrant/app/webFrontend/node_modules/lwipify/lib/index.js:42:9)
    at ImageParser.parse (/vagrant/app/webFrontend/node_modules/image-parser/lib/index.js:56:13)
    at /vagrant/app/webFrontend/node_modules/image-to-ascii/lib/index.js:98:40
    at doSeq (/vagrant/app/webFrontend/node_modules/one-by-one/lib/index.js:44:15)
    at oneByOne (/vagrant/app/webFrontend/node_modules/one-by-one/lib/index.js:66:5)
    at imageToAscii (/vagrant/app/webFrontend/node_modules/image-to-ascii/lib/index.js:97:5)
    at /vagrant/app/webFrontend/node_modules/protractor-screenshoter-plugin/index.js:143:25
    at WriteStream.<anonymous> (/vagrant/app/webFrontend/node_modules/protractor-screenshoter-plugin/index.js:68:17)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:188:7)
    at finishMaybe (_stream_writable.js:510:14)
    at afterWrite (_stream_writable.js:384:3)
    at onwrite (_stream_writable.js:374:7)
  name: 'AssertionError',
  actual: null,
  expected: 'https:',
  operator: '==',
  message: 'protocol mismatch',
  generatedMessage: false }
```

The Protractor-plugins tries to get an local image saved under `./.reports/e2e/screenshots/b65b6de0-3fc2-11e7-beba-83e02387b4aa.png` as ascii-chars. But your plugin doesn't handle this path correctly, it says that this images is a remote-url. So lwipify tries to download it.

To test this run the following code (`nodejs index.js`)
```
"use strict";

const isLocal = require("url-local");

var testArr = [
  [true, "path/to/some/file"],
  [true, "file://path/to/some/file"],
  [false, "http://ionicabizau.net"],
  [false, "ftp://file.example.com/index.html"],
  [true, "./.reports/e2e/screenshots/asd.png"],
];

testArr.forEach(function (e, i, arr) {
  console.info("\nTesting: " + e[1]);
  var r = isLocal(e[1]);
  if (r === e[0]) {
    console.info("OK");
  } else {
    console.warn("NOT OK");
    console.warn("RESULT WAS: " + r);
  }
});
```

with the package.json:
```
{
  "name": "test-url-local",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Alexander Eimer",
  "license": "MIT",
  "dependencies": {
    "url-local": "^1.1.5"
  }
}
```

The results are:
```
Testing: path/to/some/file
OK

Testing: file://path/to/some/file
OK

Testing: http://ionicabizau.net
OK

Testing: ftp://file.example.com/index.html
OK

Testing: ./.reports/e2e/screenshots/asd.png
NOT OK
RESULT WAS: false
```

So in general it would be good for this package (even if it is a small one) to have some tests!

Best regards,
Alex

PS if this Issue is resolved we should open Issues by all corresponding packages, so I can use the protractor plugin asap!

**Comment by IonicaBizau** [comment]
> So in general it would be good for this package (even if it is a small one) to have some tests!

I'm ashamed that I'm not too good in testing––I didn't pay too much attention to tests... :cry:

**Comment by IonicaBizau** [comment]
Should be fine now since I fixed the issues with the local urls in `parse-url`. 💥
